# Colors
source = ~/.config/hypr/colors.conf

# Variables
source = ~/.config/hypr/config/env.conf

# Monitors settings
source = ~/.config/hypr/config/monitors.conf

# System settings
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/misc.conf

# Visuals
source = ~/.config/hypr/config/appearance.conf
source = ~/.config/hypr/config/animations.conf

# Interaction and rules
source = ~/.config/hypr/config/keybinds.conf
source = ~/.config/hypr/config/rules.conf

# Autostart
source = ~/.config/hypr/config/autostart.conf
