# -----------------------------------------------------
# Theme & Colors
# -----------------------------------------------------
include colors.conf

# -----------------------------------------------------
# Terminal Settings
# -----------------------------------------------------
term xterm-kitty
shell zsh --login -c "tmux attach || tmux"

# -----------------------------------------------------
# Fonts & Appearance
# -----------------------------------------------------
font_size 12.0
window_padding_width 32 38
cursor_trail 3

# -----------------------------------------------------
# Window Behavior
# -----------------------------------------------------
confirm_os_window_close 0
