include colors.conf

term xterm-kitty

shell                   zsh --login -c "tmux attach || tmux"
font_size               12.0
window_padding_width    32 38
confirm_os_window_close 0
cursor_trail            3
